### ISSUE TITLE
ERROR:  ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by waseemakbar7** [ai-to-ai/Auto-Gmail-Creator#44]
Traceback (most recent call last):
  File "C:\user\Auto-Gmail-Creator\app.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 17, in <module>
    from seleniumwire.thirdparty.mitmproxy.contrib.kaitaistruct import tls_client_hello
  File "C:\Users\wasee\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\contrib\kaitaistruct\tls_client_hello.py", line 10, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by RegulusLianZai** [comment]
1. Install or Reinstall setuptools
Try installing or reinstalling setuptools using pip:
use this try
pip install --upgrade setuptools
